//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.PassengerFlights = new HashSet<PassengerFlight>();
            this.Airplanes = new HashSet<Airplane>();
        }
    
        public int F_ID { get; set; }
        public string F_Origin { get; set; }
        public string F_Destination { get; set; }
        public System.DateTime F_Date { get; set; }
        public string F_Class { get; set; }
        public Nullable<decimal> F_KidPrice { get; set; }
        public Nullable<decimal> F_LarvaPrice { get; set; }
        public Nullable<decimal> F_AdultPrice { get; set; }
        public int F_Capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerFlight> PassengerFlights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Airplane> Airplanes { get; set; }
    }
}
