//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightAgencyEntities1 : DbContext
    {
        public FlightAgencyEntities1()
            : base("name=FlightAgencyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airplane> Airplanes { get; set; }
        public virtual DbSet<ExternalCity> ExternalCities { get; set; }
        public virtual DbSet<FlightClass> FlightClasses { get; set; }
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<InternalCity> InternalCities { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<PassengerFlight> PassengerFlights { get; set; }
    }
}
