//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightClass
    {
        public int FC_ID { get; set; }
        public string FC_Name { get; set; }
        public string FC_Info { get; set; }
    }
}
