//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passenger()
        {
            this.PassengerFlights = new HashSet<PassengerFlight>();
        }
    
        public int P_ID { get; set; }
        public string P_FirstName { get; set; }
        public string P_LastName { get; set; }
        public string P_FatherName { get; set; }
        public string P_IdentityCode { get; set; }
        public string P_Sexuality { get; set; }
        public int P_Age { get; set; }
        public int P_PhoneNumber { get; set; }
        public string P_Adderess { get; set; }
        public string P_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerFlight> PassengerFlights { get; set; }
    }
}
