//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerFlight
    {
        public int P_ID { get; set; }
        public int F_ID { get; set; }
        public int SeatNmber { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
