//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE9.Models
{
    using System;
    using System.Collections.Generic;

    public partial class RequestedFlightInformation
    {
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Date { get; set; }
        public string Class { get; set; }
        public int AdultNumber { get; set; }
        public int KidNumber { get; set; }
        public int LarvaNumber { get; set; }
    }
}
