//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int U_ID { get; set; }
        public string U_FirstName { get; set; }
        public string U_LastName { get; set; }
        public string U_Username { get; set; }
        public string U_Password { get; set; }
        public int U_Grade { get; set; }
    }
}
